"""
Django settings for sampledb project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
import dj_database_url
import cloudinary

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-CHANGE-THIS-IN-PRODUCTION')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# CSRF trusted origins for Railway
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='http://localhost:8000,http://127.0.0.1:8000', cast=Csv())

# Cloudflare Proxy Configuration
# Get real client IP from Cloudflare headers
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# SSL/HTTPS settings for production (when behind Cloudflare)
if not DEBUG:
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# django-ipware configuration for Cloudflare
IPWARE_META_PRECEDENCE_ORDER = (
    'HTTP_CF_CONNECTING_IP',  # Cloudflare
    'HTTP_X_FORWARDED_FOR',   # Standard proxy header
    'HTTP_X_REAL_IP',         # Nginx
    'REMOTE_ADDR',            # Fallback
)

# Cloudflare IP ranges (trusted proxies)
# These are Cloudflare's IPv4 ranges as of 2024
# Update periodically from: https://www.cloudflare.com/ips/
IPWARE_TRUSTED_PROXY_LIST = [
    '173.245.48.0/20',
    '103.21.244.0/22',
    '103.22.200.0/22',
    '103.31.4.0/22',
    '141.101.64.0/18',
    '108.162.192.0/18',
    '190.93.240.0/20',
    '188.114.96.0/20',
    '197.234.240.0/22',
    '198.41.128.0/17',
    '162.158.0.0/15',
    '104.16.0.0/13',
    '104.24.0.0/14',
    '172.64.0.0/13',
    '131.0.72.0/22',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'cloudinary_storage',
    'cloudinary',
    'taggit',
    'samples',
    "anymail",
    'django_comments_xtd',
    'django_comments',
    'ipware',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'csp.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'sampledb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'samples.context_processors.impressum_settings',
            ],
            'libraries':{
            'custom_templatetag': 'samples.templatetags.url_helpers',

            }
        },
    },
]

WSGI_APPLICATION = 'sampledb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Use DATABASE_URL from environment if available
# Falls back to SQLite for local development
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Where collectstatic will collect static files for production
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise configuration for efficient static file serving
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Cloudinary configuration for media file storage (required)
cloudinary.config(
    cloud_name=config('CLOUDINARY_CLOUD_NAME'),
    api_key=config('CLOUDINARY_API_KEY'),
    api_secret=config('CLOUDINARY_API_SECRET'),
    secure=True
)

# Use Cloudinary for media storage
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Authentication settings
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'

# Email configuration
# For development, use console backend (prints emails to terminal)
# For production, configure SMTP settings via environment variables
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='')
SERVER_EMAIL = DEFAULT_FROM_EMAIL
# SMTP settings (if using SMTP backend)
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
# HTTP with anymail
ANYMAIL = {
    "MAILGUN_API_KEY": config("MAILGUN_API_KEY", default=""),
    "MAILGUN_SENDER_DOMAIN": config("MAILGUN_DOMAIN", default="")
}
EMAIL_TIMEOUT = 10

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Discord webhook for sample notifications
DISCORD_WEBHOOK_URL = config('DISCORD_WEBHOOK_URL', default='')  # Fallback/default
DISCORD_WEBHOOK_EASY = config('DISCORD_WEBHOOK_EASY', default='')
DISCORD_WEBHOOK_MEDIUM = config('DISCORD_WEBHOOK_MEDIUM', default='')
DISCORD_WEBHOOK_ADVANCED = config('DISCORD_WEBHOOK_ADVANCED', default='')
DISCORD_WEBHOOK_EXPERT = config('DISCORD_WEBHOOK_EXPERT', default='')

# Base URL for Discord notifications (used for sample links)
BASE_URL = config('BASE_URL', default='http://localhost:8000')

# Allow embedding only from my platform
CSP_FRAME_ANCESTORS = ["'self'", "https://malwareanalysis-for-hedgehogs.learnworlds.com"]
X_FRAME_OPTIONS = None

# Django Sites Framework (required for django-comments-xtd)
SITE_ID = 1

# Impressum/Contact Details
IMPRESSUM_NAME = config('IMPRESSUM_NAME', default='your-name-here')
IMPRESSUM_ADDRESS_LINE1 = config('IMPRESSUM_ADDRESS_LINE1', default='your-street-address')
IMPRESSUM_ADDRESS_LINE2 = config('IMPRESSUM_ADDRESS_LINE2', default='your-city-zip-country')
IMPRESSUM_PHONE = config('IMPRESSUM_PHONE', default='your-phone-number')
IMPRESSUM_EMAIL = config('IMPRESSUM_EMAIL', default='your-email-address')

# Django Comments XTD Configuration
COMMENTS_APP = 'django_comments_xtd'
COMMENTS_XTD_MAX_THREAD_LEVEL = 2  # Allow 2 levels of nested replies
COMMENTS_XTD_CONFIRM_EMAIL = False  # Disable email confirmation for comments
COMMENTS_XTD_FORM_CLASS = 'samples.forms.AuthenticatedCommentForm'  # Use custom form to hide name/email
COMMENTS_XTD_APP_MODEL_OPTIONS = {
    'samples.analysistask': {
        'allow_flagging': False,
        'allow_feedback': False,
        'show_feedback': False,
    }
}