# Generated by Django 6.0 on 2025-12-26 08:55

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate')], max_length=20, verbose_name='Course name')),
                ('section', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Section')),
                ('lecture_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Lecture number')),
                ('lecture_title', models.CharField(max_length=500, verbose_name='Lecture title')),
            ],
            options={
                'ordering': ['course_name', 'section', 'lecture_number'],
                'unique_together': {('course_name', 'section', 'lecture_number')},
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(max_length=64, unique=True, verbose_name='SHA256')),
                ('download_link', models.URLField(blank=True, max_length=500, verbose_name='Download link')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('goal', models.TextField(blank=True, verbose_name='Goal')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='easy', max_length=10, verbose_name='Difficulty level')),
                ('youtube_id', models.CharField(blank=True, max_length=32, verbose_name='YouTube ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('like_count', models.IntegerField(default=0, verbose_name='Like count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('send_discord_notification', models.BooleanField(default=True, verbose_name='Send Discord notification')),
                ('course_references', models.ManyToManyField(blank=True, related_name='samples', to='samples.coursereference', verbose_name='Course references')),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_samples', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='TaggedTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.sample')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='tools',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='samples.TaggedTools', to='taggit.Tag', verbose_name='Tools'),
        ),
    ]
