# Generated by Django 6.0 on 2025-12-26 11:07

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


def delete_course_references(apps, schema_editor):
    CourseReference = apps.get_model('samples', 'CourseReference')
    CourseReference.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Course name')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='Course URL')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='course_image')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='coursereference',
            options={'ordering': ['course__name', 'section', 'lecture_number']},
        ),
        migrations.AlterUniqueTogether(
            name='coursereference',
            unique_together=set(),
        ),
        migrations.RunPython(delete_course_references, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='coursereference',
            name='course_name',
        ),
        migrations.AddField(
            model_name='coursereference',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='samples.course', verbose_name='Course'),
        ),
        migrations.AlterUniqueTogether(
            name='coursereference',
            unique_together={('course', 'section', 'lecture_number')},
        ),
    ]
