# Generated by Django 6.0 on 2025-12-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='size',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='sample',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='sample',
            name='download_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Download link'),
        ),
        migrations.AddField(
            model_name='sample',
            name='goal',
            field=models.TextField(blank=True, verbose_name='Goal'),
        ),
        migrations.AddField(
            model_name='sample',
            name='tools',
            field=models.TextField(blank=True, verbose_name='Tools'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sha256',
            field=models.CharField(max_length=64, unique=True, verbose_name='SHA256'),
        ),
    ]
