# Generated by Django 6.0 on 2025-12-26 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_course_alter_coursereference_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sha256',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_sha256', message='Must be a valid SHA256 hash (64 hexadecimal characters)', regex='^[a-fA-F0-9]{64}$')], verbose_name='SHA256'),
        ),
    ]
