# Generated by Django 6.0 on 2025-12-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_sample_difficulty_sample_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
