# Generated by Django 6.0 on 2025-12-27 09:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_alter_sample_sha256'),
    ]

    operations = [
        # Rename the model from Sample to AnalysisTask
        migrations.RenameModel(
            old_name='Sample',
            new_name='AnalysisTask',
        ),
        # Remove unique constraint from sha256 field
        migrations.AlterField(
            model_name='analysistask',
            name='sha256',
            field=models.CharField(
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code='invalid_sha256',
                        message='Must be a valid SHA256 hash (64 hexadecimal characters)',
                        regex='^[a-fA-F0-9]{64}$'
                    )
                ],
                verbose_name='SHA256'
            ),
        ),
        # Update the foreign key in TaggedTools to reference the renamed model
        migrations.AlterField(
            model_name='taggedtools',
            name='content_object',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                to='samples.analysistask'
            ),
        ),
    ]
