# Generated by Django 6.0 on 2025-12-27 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_rename_sample_to_analysistask'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['difficulty'], name='idx_difficulty'),
        ),
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['-created_at'], name='idx_created_desc'),
        ),
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['difficulty', '-created_at'], name='idx_diff_created'),
        ),
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['sha256'], name='idx_sha256'),
        ),
    ]
