# Generated by Django 6.0 on 2025-12-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_sample_youtube_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='sample',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
