# Generated by Django 6.0 on 2025-12-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_remove_sample_youtube_url_sample_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='image',
            field=models.ImageField(blank=True, upload_to='sample_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='YouTube ID'),
        ),
    ]
