# Generated by Django 6.0 on 2025-12-27 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_analysistask_idx_difficulty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('solution_type', models.CharField(choices=[('blog', 'Blog'), ('paper', 'Paper'), ('video', 'Video')], max_length=10, verbose_name='Solution type')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('analysis_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='samples.analysistask', verbose_name='Analysis task')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('title', 'analysis_task')},
            },
        ),
    ]
