# Generated by Django 6.0 on 2025-12-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0006_sample_image_alter_sample_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='Like count'),
        ),
    ]
