# Generated by Django 6.0 on 2025-12-27 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_default_author(apps, schema_editor):
    """Set author to first superuser for existing analysis tasks"""
    AnalysisTask = apps.get_model('samples', 'AnalysisTask')
    User = apps.get_model('auth', 'User')
    
    # Get first superuser
    superuser = User.objects.filter(is_superuser=True).first()
    if superuser:
        # Update all existing tasks without an author
        AnalysisTask.objects.filter(author__isnull=True).update(author=superuser)


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0006_solution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.RunPython(set_default_author, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='analysistask',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
    ]
