# Generated by Django 6.0 on 2025-12-27 19:04

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0007_analysistask_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='sample_library_image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
            ],
            options={
                'verbose_name': 'Sample Image',
                'verbose_name_plural': 'Sample Images',
                'ordering': ['-created_at'],
            },
        ),
    ]
