# Generated by Django 6.0 on 2025-12-24 20:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0007_sample_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
