# Generated by Django 5.2.9 on 2025-12-31 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('samples', '0008_sampleimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistask',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('advanced', 'advanced'), ('expert', 'expert')], default='easy', max_length=10, verbose_name='Difficulty level'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(help_text='Action type: liked, commented, added_solution, etc.', max_length=50, verbose_name='Verb')),
                ('target_object_id', models.PositiveIntegerField()),
                ('action_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(help_text='Human-readable description of the notification', verbose_name='Description')),
                ('unread', models.BooleanField(db_index=True, default=True, verbose_name='Unread')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional JSON data (e.g., sha256, URLs)', verbose_name='Extra data')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('action_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_actions', to='contenttypes.contenttype')),
                ('actor', models.ForeignKey(help_text='The user who triggered this notification', on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_targets', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['recipient', 'unread'], name='samples_not_recipie_3a0f2b_idx'), models.Index(fields=['-timestamp'], name='samples_not_timesta_098759_idx')],
            },
        ),
    ]
