# Generated by Django 6.0 on 2025-12-25 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0008_alter_sample_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_samples', to=settings.AUTH_USER_MODEL),
        ),
    ]
