# Generated by Django 6.0 on 2025-12-25 08:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_sample_favorited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
