# Generated by Django 5.2.9 on 2025-12-31 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_alter_analysistask_difficulty_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_solutions', to=settings.AUTH_USER_MODEL, verbose_name='Liked by'),
        ),
    ]
