# Generated by Django 6.0 on 2025-12-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0010_alter_sample_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate')], max_length=20, verbose_name='Course name')),
                ('section', models.IntegerField(verbose_name='Section')),
                ('video_title', models.TextField(verbose_name='Video title')),
            ],
            options={
                'ordering': ['course_name', 'section'],
                'unique_together': {('course_name', 'section', 'video_title')},
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='course_references',
            field=models.ManyToManyField(blank=True, related_name='samples', to='samples.coursereference', verbose_name='Course references'),
        ),
    ]
