# Generated by Django 5.2.9 on 2026-01-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0010_solution_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='content',
            field=models.TextField(blank=True, help_text='Markdown content for on-site solutions', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('paper', 'Paper'), ('video', 'Video'), ('onsite', 'On-Site Article')], max_length=10, verbose_name='Solution type'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL'),
        ),
    ]
