# Generated by Django 6.0 on 2025-12-25 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0011_coursereference_sample_course_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereference',
            name='section',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='coursereference',
            name='video_title',
            field=models.CharField(max_length=500, verbose_name='Video title'),
        ),
    ]
