# Generated by Django 5.2.9 on 2026-01-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0011_solution_content_alter_solution_solution_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='hidden_until',
            field=models.DateTimeField(blank=True, help_text='Date and time when this solution becomes visible. Leave blank for immediate visibility.', null=True, verbose_name='Hidden until'),
        ),
    ]
