# Generated by Django 5.2.9 on 2026-01-08 03:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0012_solution_hidden_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='platform',
            field=models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux'), ('macos', 'MacOS'), ('ios', 'iOS'), ('android', 'Android'), ('multiple', 'Multiple'), ('other', 'Other')], default='windows', max_length=20, verbose_name='Platform'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['solution_type'], name='idx_solution_type'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['analysis_task', 'solution_type'], name='idx_task_type'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['-created_at'], name='idx_solution_created'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['author'], name='idx_solution_author'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['hidden_until'], name='idx_hidden_until'),
        ),
    ]
