# Generated by Django 6.0 on 2025-12-25 09:41

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0012_alter_coursereference_section_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='tools',
        ),
        migrations.CreateModel(
            name='TaggedTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.sample')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='tools',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='samples.TaggedTools', to='taggit.Tag', verbose_name='Tools'),
        ),
    ]
