# Generated by Django 5.2.9 on 2026-02-01 04:16

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0013_analysistask_platform_solution_idx_solution_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='editor_images')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_images', to=settings.AUTH_USER_MODEL, verbose_name='Uploader')),
            ],
            options={
                'verbose_name': 'Editor Image',
                'verbose_name_plural': 'Editor Images',
                'ordering': ['-created_at'],
            },
        ),
    ]
