# Generated by Django 6.0 on 2025-12-25 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0013_remove_sample_tools_taggedtools_sample_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='send_discord_notification',
            field=models.BooleanField(default=True, verbose_name='Send Discord notification'),
        ),
    ]
