# Generated by Django 5.2.9 on 2026-02-01 05:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0014_editorimage'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='View count'),
        ),
        migrations.AddField(
            model_name='solution',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='View count'),
        ),
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['-view_count'], name='idx_view_count'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['-view_count'], name='idx_solution_view_count'),
        ),
    ]
