# Generated by Django 6.0 on 2025-12-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0015_alter_sample_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
    ]
