# Generated by Django 5.2.9 on 2026-02-21 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0015_analysistask_view_count_solution_view_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='content',
            field=models.TextField(blank=True, help_text='Markdown content for on-site solutions (deprecated, use article field)', verbose_name='Content'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(help_text='Markdown content', verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('view_count', models.IntegerField(default=0, verbose_name='View count')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='solution',
            name='article',
            field=models.OneToOneField(blank=True, help_text='Article content for on-site solutions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='samples.article', verbose_name='Article'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author'], name='idx_article_author'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-updated_at'], name='idx_article_updated'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-created_at'], name='idx_article_created'),
        ),
    ]
