# Generated by Django 5.2.9 on 2026-02-21 11:31

from django.db import migrations


def transfer_solution_view_counts_to_articles(apps, schema_editor):
    """Transfer view_count from solutions to their associated articles"""
    Solution = apps.get_model('samples', 'Solution')
    Article = apps.get_model('samples', 'Article')
    
    # Get all solutions that have an article attached
    solutions_with_articles = Solution.objects.filter(article__isnull=False).select_related('article')
    
    # Transfer view counts
    for solution in solutions_with_articles:
        if solution.view_count > 0:
            # Update the article's view_count with the solution's view_count
            Article.objects.filter(id=solution.article.id).update(
                view_count=solution.view_count
            )
    
    print(f"Transferred view counts from {solutions_with_articles.count()} solutions to their articles")


def reverse_transfer_view_counts(apps, schema_editor):
    """Reverse migration - not really possible to restore data accurately"""
    # We can't accurately reverse this, but we provide a no-op for consistency
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0017_migrate_onsite_solutions_to_articles'),
    ]

    operations = [
        # First, transfer view counts from solutions to articles
        migrations.RunPython(
            transfer_solution_view_counts_to_articles,
            reverse_transfer_view_counts
        ),
        # Then remove the index
        migrations.RemoveIndex(
            model_name='solution',
            name='idx_solution_view_count',
        ),
        # Finally remove the field
        migrations.RemoveField(
            model_name='solution',
            name='view_count',
        ),
    ]
